services:
  postgres:
    image: postgres:16-alpine
    container_name: flashshop-postgres
    environment:
      POSTGRES_USER: flashshop
      POSTGRES_PASSWORD: flashshop_dev
      POSTGRES_DB: flashshop
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: flashshop-redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: flashshop-nginx
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres-data:
